---
# Copyright (c) IBM Corporation 2020

# tasks file for unpack-restore-data-sets
- name: Raise error if required variables are not set
  fail:
    msg: Missing at least one required variable.
  failed_when: terse_data_set is not defined or
    terse_data_set == "" or
    new_hlq is not defined or
    new_hlq|length == 0

- name: Estimate the total used size of all provided data sets
  include_role:
    name: get-estimated-size-of-data-sets
  vars:
    data_sets: "{{ [terse_data_set] }}"
  # if running transfer-data-sets.yml it will pass a more accurate
  # estimated size based on original data set sizes
  when: size_in_cyls is not defined

- block:
  - name: Get HLQ of user
    command: hlq
    register: hlq_name

  - name: "Restore all datasets from backup"
    ibm.ibm_zos_core.zos_backup_restore:
      operation: restore
      data_sets:
        include: "{{ data_sets_to_restore }}"
      backup_name: "{{ terse_data_set }}"
      hlq: "{{ new_hlq }}"
      space: "{{ size_in_cyls.get('primary') }}"
      space_type: cyl
      volume: "{{ output_volume if output_volume is defined and output_volume | default(false) else omit }}"
      overwrite: "{{ True if replace is defined and replace else False }}"
    register: response
    when: data_sets_to_dump is defined and data_sets_to_dump|length > 0

  - name: "Restore all datasets from backup"
    ibm.ibm_zos_core.zos_backup_restore:
      operation: restore
      backup_name: "{{ terse_data_set }}"
      hlq: "{{ new_hlq }}"
      space: "{{ size_in_cyls.get('primary') }}"
      space_type: cyl
      volume: "{{ output_volume if output_volume is defined and output_volume | default(false) else omit }}"
      overwrite: "{{ True if replace is defined and replace else False }}"
    register: response
    when: data_sets_to_dump is not defined or data_sets_to_dump|length == 0
  always:
    - debug:
        var: response

    - name: Clean up terse data set
      ibm.ibm_zos_core.zos_data_set:
        name: "{{ terse_data_set }}"
        state: absent
      when: delete
