---
# Online Change Services
- name: Online Change Services
  collections:
    - ibm.ibm_zos_core
    - ibm.ibm_zos_ims

  block:

    - block:
      - set_fact:
          eager_role_path: '{{role_path}}'

# ------------------------------------------------------------------------------------------------------ DFSENOLC
      - name: Enable IMS OLC
        zos_copy:
          src: "{{ DFS_AUTH_LIB_HLQ1 }}.{{ DFS_AUTH_LIB_HLQ2 }}.PROCLIB(DFSMREC)"
          dest: "{{ DFS_AUTH_LIB_HLQ1 }}.{{ DFS_AUTH_LIB_HLQ2 }}.MODSTAT"
          remote_src: true
        when: enable_olc
# ------------------------------------------------------------------------------------------------------

    - block:
      - set_fact:
          eager_role_path: '{{role_path}}'

      # Send the template over
# ------------------------------------------------------------------------------------------------------
# Calls a procedure, cannot convert, plus, the procedure was defined on the execution of ims_initialize
# ------------------------------------------------------------------------------------------------------


      - include_role:
          name: send-template
        vars:
          path: '{{ eager_role_path }}/templates/DFS4ACTV.j2'

      when: active_libs and not provision

    # We need a module for the online change utility, no way around it
    - name: Establish active libs
      zos_job_submit:
        src: '{{ uss_file_path }}/DFS4ACTV.j2'
        location: USS
        wait: true
        wait_time_s: 30
      when: active_libs