---
################################################################################
# Copyright (c) IBM Corporation 2021
################################################################################

################################################################################
# the path to the root of IBM python installation
################################################################################
# PYZ: "path_to_python"
PYZ: "/usr/lpp/IBM/cyp/v3r8/pyz"
################################################################################
# the path to root of ZOAU installation
################################################################################
ZOAU: "/zoau/v1.1.1-ptf1"
# ZOAU: "path_to_zoau"
# ZOAU: "/zoau/v1.1.0-ga"
# ZOAU: "/zoau/v1.1.1"

