---
- hosts: zos_host
  collections:
    - ibm.ibm_zos_core
    - ibm.ibm_zos_ims
  gather_facts: false
  environment: '{{ environment_vars }}'

  tasks:

  - name: issue tso command
    zos_tso_command:
      commands:
        - time
    ignore_errors: yes
    ignore_unreachable: yes

  - meta: clear_host_errors

  - name: Display IMS active
    ims_command:
      command: "DIS ACT"
      plex: PLEX1

  - name: sleep for 30 minutes
    raw:
      sleep 1800;
    delegate_to: localhost