---
- hosts: zos_host
  collections:
    - ibm.ibm_zos_core
    - ibm.ibm_zos_ims
  gather_facts: false
  environment: '{{ environment_vars }}'

  tasks:
  # - name: Ping the z/OS host
  #   zos_ping:
  #   register: result

  - name: issue tso command
    zos_tso_command:
      commands:
        - time
    ignore_errors: yes

  - name: sleep for a bit
    raw:
      sleep 600;
    delegate_to: localhost

  - name: Display IMS active
    ims_command:
      command: "DIS ACT"
      plex: PLEX1