---
# Copyright (c) IBM Corporation 2020

# tasks file for dump-pack-ftp-data-sets
- name: Raise error if required variables are not set
  fail:
    msg: Missing at least one required variable.
  failed_when: data_sets_to_dump is not defined or
    data_sets_to_dump|length == 0 or
    target_hostname is not defined or
    target_hostname == "" or
    target_user is not defined or
    target_user == "" or
    target_password is not defined or
    target_password == ""

- name: Estimate the total used size of all provided data sets
  include_role:
    name: get-estimated-size-of-data-sets
  vars:
    data_sets: "{{ data_sets_to_dump }}"

- block:

  - name: Get HLQ of user
    command: hlq
    register: hlq_name

  - name: get temporary data set name
    command: mvstmp {{ hlq_name.stdout }}
    register: backup_name

  - name: "Backup"
    ibm.ibm_zos_core.zos_backup_restore:
      operation: backup
      data_sets:
        include: "{{ data_sets_to_dump }}"
      backup_name: "{{ backup_name.stdout }}"
      space: "{{ size_in_cyls.get('primary') }}"
      space_type: cyl
      overwrite: yes
    register: response

  - name: Determine name to use for target data set
    set_fact:
      target_data_set: "{{ target_data_set if target_data_set is defined and target_data_set else backup_name.stdout }}"
    run_once: true

  - block:

    - name: FTP the terse data set to destination
      ibm.ibm_zos_core.zos_mvs_raw:
        program_name: ftp
        auth: yes
        dds:
          - dd_output:
              dd_name: output
              return_content:
                type: text
          - dd_input:
              dd_name: input
              content: "{{ lookup('template', '../templates/ftp-commands.j2') }}"
      register: ftp_response
      failed_when: ftp_response.ret_code.code > 0
    always:
      - debug:
          var: ftp_response
        when: ftp_response is defined
  always:
    - debug:
        var: response
    - name: Clean up archive data set
      ibm.ibm_zos_core.zos_data_set:
        name: "{{ backup_name.stdout }}"
        state: absent
      when: delete and backup_name.stdout is defined and backup_name.stdout|length > 0
