- hosts: all
  collections:
    - ibm.ibm_zos_core
  gather_facts: no
  environment: "{{ environment_vars }}"
  tasks:
    - block:
        - name: Qry trans
          zos_mvs_raw:
            pgm: CSLUSPOC
            auth: no
            parm: "IMSPLEX=PLEX1,ROUTE=IMSO,WAIT=30"
            verbose: true
            dds:
              - dd_concat:
                  dd_name: steplib
                  dds:
                    - dd_data_set:
                        data_set_name: "ANDYN.TEST.ZOS.COPY.SDFSRES"
                        disposition: shr
                        disposition_normal: keep
                        disposition_abnormal: keep
                    - dd_data_set:
                        data_set_name: "DFS.V15R1M0.SDFSRESL"
                        disposition: shr
                        disposition_normal: keep
                        disposition_abnormal: keep
              - dd_output:
                  dd_name: sysprint
                  return_content:
                    type: text
              - dd_input:
                  dd_name: sysin
                  content: " QRY TRAN NAME(IB*, TB*) SHOW(ALL)"
      always:
        - debug:
            var: response
          when: response is defined
