- name: Backup and restore data sets
  hosts: zsystem
  collections:
    - ibm.ibm_zos_core
  gather_facts: false
  environment: "{{ environment_vars }}"

  tasks:
    - name: Output data sets to backup
      shell: dls user.private.*
      register: response

    - debug:
        var: response.stdout_lines

    - name: Remove datasets matching desired restore hlq
      shell: drm -f testme.**

    - name: "Backup all datasets matching pattern USER.** to data set MY.BACKUP"
      zos_backup_restore:
        operation: backup
        data_sets:
          include: user.private.*
        backup_name: IMSTESTL.BACKUP
        overwrite: yes

    - block:
        - name: "Restore all datasets from backup"
          zos_backup_restore:
            operation: restore
            backup_name: IMSTESTL.BACKUP
            hlq: testme
          register: response
      always:
        - debug:
            var: response

    - name: Output data sets that were restored
      shell: dls testme.**
      register: response

    - debug:
        var: response.stdout_lines
