---
# inventory.yml file for the sample playbooks of the IBM Z HMC Collection

default:  # A group nickname

  hosts:

    myhmc13:  # An HMC nickname (must match the nickname in the vault file)
      ansible_host: 10.11.12.13

    # ... more HMC entries for this group, as needed

# ... more groups, as needed
